#!/usr/bin/env node

var fs = require('fs');
var source = require('./src/npm-all-1108.json');
var Package = require('./lib/package').Package;

var pkgs = Object.keys(source).map(function (k) { return source[k]; });

var results = {};

var clientSideTemplatePackages = pkgs.
    filter(function (pkgMeta) {
        return pkgMeta && pkgMeta.name;
    }).
    map(Package.create).
    //filter(function (p) {
        //// keyword/description contains either client or template
        //return (-1 !== p.keyword.indexOf('client')) ||
               //(-1 !== p.keyword.indexOf('template')) &&
               //((-1 !== p.desc.indexOf('client')) ||
               //(-1 !== p.desc.indexOf('template')));
    //}).
    forEach(function (p) {
        results[p.name] = p.data;
    });

fs.writeFileSync('./output/client-template.json', JSON.stringify(results));
