#!/usr/bin/env node

var packages = require('./src/npm-all-1108.json');

var pkgs = Object.keys(packages).map(function (k) { return packages[k]; });

Package = {
    create: function () {
    }
};
function Package() {}

function contains(query, key) {
    return function (query) {
    };
}

var result = pkgs.
    filter(function (p) {
        return p.description && -1 !== p.description.indexOf('template');
    }).
    filter(function (p) {
        return Array.isArray(p.keywords) && -1 === p.keywords.join(' ').indexOf('template');
    });
