#!/usr/bin/env node

var fs = require('fs');
var Rx = require('rx');
var downloadNpmSource = require('./download-npm-source');

const DAY = 24 * 60 * 60 * 1000;
const WEEK = 7 * DAY;

Rx.Observable.timer(0, DAY).
    subscribe(
        function () {
            downloadNpmSource.run.subscribe(function (path) {
                var packages = fs.readFileSync(path);
            });
        },
        console.error
    );
